name: e_commerce
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.13.0-227.0.dev

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  flutter_launcher_icons: ^0.13.1
  
  flutter_lints: ^6.0.0

flutter_launcher_icons:
  image_path: "web/icons/icon.png"
  android: true
  ios: true  

flutter:
  uses-material-design: true

  assets:
    - web/icons/item_img/Pork_and_Eggs_with_salad_hamburger.jpg

