// lib/data/menu_data.dart

class MenuData {
  // 將餐點資料宣告為 static final，讓其他檔案可以直接讀取，不需重複實例化
  static final Map<String, List<Map<String, dynamic>>> categories = {
    '套餐': [
        
        //
      {'name': '兒童套餐 A (60元)：小雞塊  薯條  雞堡熱狗', 'price': 75,'image':'web/icons/item_img/Pork_and_Eggs_with_salad_hamburger.jpg','height':100,'width':100},
      {'name': '招牌套餐 (70元)：蔓越莓花生醬  蔬菜沙拉  蛋', 'price': 75,'image':'web/icons/item_img/Pork_and_Eggs_with_salad_hamburger.jpg','height':100,'width':100},
      {'name': '快樂套餐 (70元)：法國吐司  黃金脆薯', 'price': 75,'image':'web/icons/item_img/Pork_and_Eggs_with_salad_hamburger.jpg','height':100,'width':100},
      {'name': '活力套餐 (80元)：薯條  德式香腸  四角薯餅  荷包蛋', 'price': 75,'image':'web/icons/item_img/Pork_and_Eggs_with_salad_hamburger.jpg','height':100,'width':100},    
      {'name': '千層蛋燒套餐 (90元)：千層蛋燒（香濃起司、玉米、蛋）＋ 蔬菜沙拉', 'price': 75,'image':'web/icons/item_img/Pork_and_Eggs_with_salad_hamburger.jpg','height':100,'width':100},
      {'name': '法式套餐 (85元)：法式麵包抹蒜香  蔬菜沙拉  培根  薯餅  蛋', 'price': 75,'image':'web/icons/item_img/Pork_and_Eggs_with_salad_hamburger.jpg','height':100,'width':100},
      {'name': '美式鬆餅特餐 (90元)：鬆餅  美式炒蛋  培根', 'price': 75,'image':'web/icons/item_img/Pork_and_Eggs_with_salad_hamburger.jpg','height':100,'width':100},
      {'name': 'A、B、C餐飯 (85元)', 'price': 75,'image':'web/icons/item_img/Pork_and_Eggs_with_salad_hamburger.jpg','height':100,'width':100},
      {'name': '幸福套餐 (90元)：法國吐司  德式香肠  蔬菜沙拉', 'price': 75,'image':'web/icons/item_img/Pork_and_Eggs_with_salad_hamburger.jpg','height':100,'width':100},
      {'name': '樂活套餐 (95元)：香蒜麵包抹奶油  薯餅蛋塔  黑胡椒豬排  蔬菜沙拉', 'price': 75,'image':'web/icons/item_img/Pork_and_Eggs_with_salad_hamburger.jpg','height':100,'width':100},
      {'name': '都會套餐 (100元)：貝果  藍莓醬  美式炒蛋  火腿  薯餅  蔬菜沙拉', 'price': 75,'image':'web/icons/item_img/Pork_and_Eggs_with_salad_hamburger.jpg','height':100,'width':100},
      {'name': '蘿蔔糕特餐 (95元)', 'price': 75,'image':'web/icons/item_img/Pork_and_Eggs_with_salad_hamburger.jpg','height':100,'width':100},
    ],
        '中式餐點': [
      {'name': '全麥蛋餅', 'price': 25, 'image': 'web/icons/item_img/Pork_and_Eggs_with_salad_hamburger.jpg', 'height': 100, 'width': 100},
      {'name': '芝士蛋餅', 'price': 35, 'image': 'web/icons/item_img/Pork_and_Eggs_with_salad_hamburger.jpg', 'height': 100, 'width': 100},
      {'name': '火腿蛋餅', 'price': 35, 'image': 'web/icons/item_img/Pork_and_Eggs_with_salad_hamburger.jpg', 'height': 100, 'width': 100},
      {'name': '玉米蛋餅', 'price': 35, 'image': 'web/icons/item_img/Pork_and_Eggs_with_salad_hamburger.jpg', 'height': 100, 'width': 100},
      {'name': '肉鬆蛋餅', 'price': 35, 'image': 'web/icons/item_img/Pork_and_Eggs_with_salad_hamburger.jpg', 'height': 100, 'width': 100},
      {'name': '熱狗蛋餅', 'price': 35, 'image': 'web/icons/item_img/Pork_and_Eggs_with_salad_hamburger.jpg', 'height': 100, 'width': 100},
      {'name': '培根蛋餅', 'price': 35, 'image': 'web/icons/item_img/Pork_and_Eggs_with_salad_hamburger.jpg', 'height': 100, 'width': 100},
      {'name': '鮮蔬蛋餅', 'price': 35, 'image': 'web/icons/item_img/Pork_and_Eggs_with_salad_hamburger.jpg', 'height': 100, 'width': 100},
      {'name': '泡菜蛋餅', 'price': 35, 'image': 'web/icons/item_img/Pork_and_Eggs_with_salad_hamburger.jpg', 'height': 100, 'width': 100},
      {'name': '鮪魚蛋餅', 'price': 40, 'image': 'web/icons/item_img/Pork_and_Eggs_with_salad_hamburger.jpg', 'height': 100, 'width': 100},
      {'name': '豬排蛋餅', 'price': 45, 'image': 'web/icons/item_img/Pork_and_Eggs_with_salad_hamburger.jpg', 'height': 100, 'width': 100},
      {'name': '薯餅蛋餅', 'price': 45, 'image': 'web/icons/item_img/Pork_and_Eggs_with_salad_hamburger.jpg', 'height': 100, 'width': 100},
      // 點心、麵食與主食
      {'name': '板條', 'price': 50, 'image': 'web/icons/item_img/Pork_and_Eggs_with_salad_hamburger.jpg', 'height': 100, 'width': 100},
      {'name': '日式涼麵', 'price': 40, 'image': 'web/icons/item_img/Pork_and_Eggs_with_salad_hamburger.jpg', 'height': 100, 'width': 100},
      {'name': '薯餅蛋塔', 'price': 45, 'image': 'web/icons/item_img/Pork_and_Eggs_with_salad_hamburger.jpg', 'height': 100, 'width': 100},
      {'name': '湯種法國吐司', 'price': 35, 'image': 'web/icons/item_img/Pork_and_Eggs_with_salad_hamburger.jpg', 'height': 100, 'width': 100},
      {'name': '蘿蔔糕', 'price': 25, 'image': 'web/icons/item_img/Pork_and_Eggs_with_salad_hamburger.jpg', 'height': 100, 'width': 100},
      {'name': '泡菜蘿蔔糕', 'price': 35, 'image': 'web/icons/item_img/Pork_and_Eggs_with_salad_hamburger.jpg', 'height': 100, 'width': 100},
      {'name': '鐵板麵（蘑菇/黑胡椒）', 'price': 35, 'image': 'web/icons/item_img/Pork_and_Eggs_with_salad_hamburger.jpg', 'height': 100, 'width': 100},
      {'name': '荷包蛋（全熟/半熟）', 'price': 15, 'image': 'web/icons/item_img/Pork_and_Eggs_with_salad_hamburger.jpg', 'height': 100, 'width': 100},
      {'name': '蔥抓餅', 'price': 25, 'image': 'web/icons/item_img/Pork_and_Eggs_with_salad_hamburger.jpg', 'height': 100, 'width': 100},
      {'name': '泡菜蔥抓餅', 'price': 35, 'image': 'web/icons/item_img/Pork_and_Eggs_with_salad_hamburger.jpg', 'height': 100, 'width': 100},
      {'name': '宮保雞丁鐵板麵', 'price': 50, 'image': 'web/icons/item_img/Pork_and_Eggs_with_salad_hamburger.jpg', 'height': 100, 'width': 100},
      {'name': '日式辛炒烏龍', 'price': 65, 'image': 'web/icons/item_img/Pork_and_Eggs_with_salad_hamburger.jpg', 'height': 100, 'width': 100},
      {'name': '雞絲蛋麵', 'price': 40, 'image': 'web/icons/item_img/Pork_and_Eggs_with_salad_hamburger.jpg', 'height': 100, 'width': 100},
    ],
    '經典麵包系列': [
      {'name': '鮮蔬歐式招牌堡/丹麥漢堡', 'price': 40, 'image': 'web/icons/item_img/Pork_and_Eggs_with_salad_hamburger.jpg', 'height': 100, 'width': 100},
      {'name': '歐姆蛋歐式招牌堡/丹麥漢堡', 'price': 45, 'image': 'web/icons/item_img/Pork_and_Eggs_with_salad_hamburger.jpg', 'height': 100, 'width': 100},
      {'name': '鮪魚歐式招牌堡/丹麥漢堡', 'price': 45, 'image': 'web/icons/item_img/Pork_and_Eggs_with_salad_hamburger.jpg', 'height': 100, 'width': 100},
      {'name': '檸檬雞歐式招牌堡/丹麥漢堡', 'price': 50, 'image': 'web/icons/item_img/Pork_and_Eggs_with_salad_hamburger.jpg', 'height': 100, 'width': 100},
      {'name': '燻雞歐式招牌堡/丹麥漢堡', 'price': 50, 'image': 'web/icons/item_img/Pork_and_Eggs_with_salad_hamburger.jpg', 'height': 100, 'width': 100},
      {'name': '培根芝士歐式招牌堡/丹麥漢堡', 'price': 55, 'image': 'web/icons/item_img/Pork_and_Eggs_with_salad_hamburger.jpg', 'height': 100, 'width': 100},
      {'name': '香烤雞腿歐式招牌堡/丹麥漢堡', 'price': 55, 'image': 'web/icons/item_img/Pork_and_Eggs_with_salad_hamburger.jpg', 'height': 100, 'width': 100},
      {'name': '卡啦雞腿（原/辣）歐式招牌堡/丹麥漢堡', 'price': 60, 'image': 'web/icons/item_img/Pork_and_Eggs_with_salad_hamburger.jpg', 'height': 100, 'width': 100},
      {'name': '超厚牛肉芝士歐式招牌堡/丹麥漢堡', 'price': 75, 'image': 'web/icons/item_img/Pork_and_Eggs_with_salad_hamburger.jpg', 'height': 100, 'width': 100},
    ],
    '貝果系列': [
      {'name': '鮮蔬貝果/丹麥堡', 'price': 40, 'image': 'web/icons/item_img/Pork_and_Eggs_with_salad_hamburger.jpg', 'height': 100, 'width': 100},
      {'name': '歐姆蛋貝果/丹麥堡', 'price': 45, 'image': 'web/icons/item_img/Pork_and_Eggs_with_salad_hamburger.jpg', 'height': 100, 'width': 100},
      {'name': '鮪魚貝果/丹麥堡', 'price': 45, 'image': 'web/icons/item_img/Pork_and_Eggs_with_salad_hamburger.jpg', 'height': 100, 'width': 100},
      {'name': '檸檬雞貝果/丹麥堡', 'price': 50, 'image': 'web/icons/item_img/Pork_and_Eggs_with_salad_hamburger.jpg', 'height': 100, 'width': 100},
      {'name': '燻雞貝果/丹麥堡', 'price': 50, 'image': 'web/icons/item_img/Pork_and_Eggs_with_salad_hamburger.jpg', 'height': 100, 'width': 100},
      {'name': '培根芝士貝果/丹麥堡', 'price': 55, 'image': 'web/icons/item_img/Pork_and_Eggs_with_salad_hamburger.jpg', 'height': 100, 'width': 100},
      {'name': '香烤雞腿貝果/丹麥堡', 'price': 55, 'image': 'web/icons/item_img/Pork_and_Eggs_with_salad_hamburger.jpg', 'height': 100, 'width': 100},
      {'name': '卡啦雞腿（原/辣）貝果/丹麥堡', 'price': 60, 'image': 'web/icons/item_img/Pork_and_Eggs_with_salad_hamburger.jpg', 'height': 100, 'width': 100},
      {'name': '超厚牛肉芝士貝果/丹麥堡', 'price': 75, 'image': 'web/icons/item_img/Pork_and_Eggs_with_salad_hamburger.jpg', 'height': 100, 'width': 100},
    ],
    '捲餅系列': [
      {'name': '燻雞捲餅', 'price': 45, 'image': 'web/icons/item_img/Pork_and_Eggs_with_salad_hamburger.jpg', 'height': 100, 'width': 100},
      {'name': '檸檬雞捲餅', 'price': 45, 'image': 'web/icons/item_img/Pork_and_Eggs_with_salad_hamburger.jpg', 'height': 100, 'width': 100},
      {'name': '脆雞捲餅', 'price': 45, 'image': 'web/icons/item_img/Pork_and_Eggs_with_salad_hamburger.jpg', 'height': 100, 'width': 100},
      {'name': '德式香腸捲餅', 'price': 45, 'image': 'web/icons/item_img/Pork_and_Eggs_with_salad_hamburger.jpg', 'height': 100, 'width': 100},
      {'name': '雞柳條捲餅', 'price': 45, 'image': 'web/icons/item_img/Pork_and_Eggs_with_salad_hamburger.jpg', 'height': 100, 'width': 100},
      {'name': '黑胡椒豬排捲餅', 'price': 45, 'image': 'web/icons/item_img/Pork_and_Eggs_with_salad_hamburger.jpg', 'height': 100, 'width': 100},
    ],
    '早午餐系列': [
      {'name': '茄汁檸檬雞義大利麵', 'price': 90, 'image': 'web/icons/item_img/Pork_and_Eggs_with_salad_hamburger.jpg', 'height': 100, 'width': 100},
      {'name': '奶油培根義大利麵', 'price': 90, 'image': 'web/icons/item_img/Pork_and_Eggs_with_salad_hamburger.jpg', 'height': 100, 'width': 100},
      {'name': '青醬燻雞義大利麵', 'price': 90, 'image': 'web/icons/item_img/Pork_and_Eggs_with_salad_hamburger.jpg', 'height': 100, 'width': 100},
      {'name': '燉飯（茄汁/奶油/青醬）', 'price': 95, 'image': 'web/icons/item_img/Pork_and_Eggs_with_salad_hamburger.jpg', 'height': 100, 'width': 100},
      {'name': '德式百匯', 'price': 110, 'image': 'web/icons/item_img/Pork_and_Eggs_with_salad_hamburger.jpg', 'height': 100, 'width': 100},
      {'name': '澳洲純牛漢堡排', 'price': 125, 'image': 'web/icons/item_img/Pork_and_Eggs_with_salad_hamburger.jpg', 'height': 100, 'width': 100},
      {'name': '大法式佐紅醬餐', 'price': 120, 'image': 'web/icons/item_img/Pork_and_Eggs_with_salad_hamburger.jpg', 'height': 100, 'width': 100},
      {'name': '脆薯烤雞（麵/飯）', 'price': 130, 'image': 'web/icons/item_img/Pork_and_Eggs_with_salad_hamburger.jpg', 'height': 100, 'width': 100},
      {'name': '泰式卡啦脆雞', 'price': 140, 'image': 'web/icons/item_img/Pork_and_Eggs_with_salad_hamburger.jpg', 'height': 100, 'width': 100},
      {'name': '美式鄉村餐', 'price': 145, 'image': 'web/icons/item_img/Pork_and_Eggs_with_salad_hamburger.jpg', 'height': 100, 'width': 100},
    ],
    '漢堡／湯種吐司系列': [
      {'name': '火腿吐司/漢堡', 'price': 25, 'image': 'web/icons/item_img/Pork_and_Eggs_with_salad_hamburger.jpg', 'height': 100, 'width': 100},
      {'name': '肉鬆吐司/漢堡', 'price': 25, 'image': 'web/icons/item_img/Pork_and_Eggs_with_salad_hamburger.jpg', 'height': 100, 'width': 100},
      {'name': '鮮蔬吐司/漢堡', 'price': 30, 'image': 'web/icons/item_img/Pork_and_Eggs_with_salad_hamburger.jpg', 'height': 100, 'width': 100},
      {'name': '素肉鬆吐司/漢堡（素）', 'price': 30, 'image': 'web/icons/item_img/Pork_and_Eggs_with_salad_hamburger.jpg', 'height': 100, 'width': 100},
      {'name': '豬肉吐司/漢堡', 'price': 35, 'image': 'web/icons/item_img/Pork_and_Eggs_with_salad_hamburger.jpg', 'height': 100, 'width': 100},
      {'name': '香雞吐司/漢堡', 'price': 35, 'image': 'web/icons/item_img/Pork_and_Eggs_with_salad_hamburger.jpg', 'height': 100, 'width': 100},
      {'name': '鮪魚吐司/漢堡', 'price': 35, 'image': 'web/icons/item_img/Pork_and_Eggs_with_salad_hamburger.jpg', 'height': 100, 'width': 100},
      {'name': '薯餅吐司/漢堡', 'price': 30, 'image': 'web/icons/item_img/Pork_and_Eggs_with_salad_hamburger.jpg', 'height': 100, 'width': 100},
      {'name': '歐姆蛋吐司/漢堡', 'price': 40, 'image': 'web/icons/item_img/Pork_and_Eggs_with_salad_hamburger.jpg', 'height': 100, 'width': 100},
      {'name': '黑胡椒豬排吐司/漢堡', 'price': 40, 'image': 'web/icons/item_img/Pork_and_Eggs_with_salad_hamburger.jpg', 'height': 100, 'width': 100},
      {'name': '燻雞吐司/漢堡', 'price': 40, 'image': 'web/icons/item_img/Pork_and_Eggs_with_salad_hamburger.jpg', 'height': 100, 'width': 100},
      {'name': '檸檬雞吐司/漢堡', 'price': 40, 'image': 'web/icons/item_img/Pork_and_Eggs_with_salad_hamburger.jpg', 'height': 100, 'width': 100},
      {'name': '培根芝士吐司/漢堡', 'price': 45, 'image': 'web/icons/item_img/Pork_and_Eggs_with_salad_hamburger.jpg', 'height': 100, 'width': 100},
      {'name': '香烤雞腿吐司/漢堡', 'price': 45, 'image': 'web/icons/item_img/Pork_and_Eggs_with_salad_hamburger.jpg', 'height': 100, 'width': 100},
      {'name': '卡啦雞腿（原/辣）吐司/漢堡', 'price': 50, 'image': 'web/icons/item_img/Pork_and_Eggs_with_salad_hamburger.jpg', 'height': 100, 'width': 100},
      {'name': '烤總匯吐司/漢堡', 'price': 60, 'image': 'web/icons/item_img/Pork_and_Eggs_with_salad_hamburger.jpg', 'height': 100, 'width': 100},
      {'name': '超厚牛肉芝士吐司/漢堡', 'price': 65, 'image': 'web/icons/item_img/Pork_and_Eggs_with_salad_hamburger.jpg', 'height': 100, 'width': 100},
    ],
    '烤吐司系列': [
      {'name': '草莓薄片', 'price': 15, 'image': 'web/icons/item_img/Pork_and_Eggs_with_salad_hamburger.jpg', 'height': 100, 'width': 100},
      {'name': '草莓湯種厚片', 'price': 20, 'image': 'web/icons/item_img/Pork_and_Eggs_with_salad_hamburger.jpg', 'height': 100, 'width': 100},
      {'name': '草莓貝果', 'price': 30, 'image': 'web/icons/item_img/Pork_and_Eggs_with_salad_hamburger.jpg', 'height': 100, 'width': 100},
      {'name': '奶酥薄片', 'price': 15, 'image': 'web/icons/item_img/Pork_and_Eggs_with_salad_hamburger.jpg', 'height': 100, 'width': 100},
      {'name': '奶酥湯種厚片', 'price': 20, 'image': 'web/icons/item_img/Pork_and_Eggs_with_salad_hamburger.jpg', 'height': 100, 'width': 100},
      {'name': '奶酥貝果', 'price': 30, 'image': 'web/icons/item_img/Pork_and_Eggs_with_salad_hamburger.jpg', 'height': 100, 'width': 100},
      {'name': '花生薄片', 'price': 15, 'image': 'web/icons/item_img/Pork_and_Eggs_with_salad_hamburger.jpg', 'height': 100, 'width': 100},
      {'name': '花生湯種厚片', 'price': 20, 'image': 'web/icons/item_img/Pork_and_Eggs_with_salad_hamburger.jpg', 'height': 100, 'width': 100},
      {'name': '花生貝果', 'price': 30, 'image': 'web/icons/item_img/Pork_and_Eggs_with_salad_hamburger.jpg', 'height': 100, 'width': 100},
      {'name': '奶油薄片', 'price': 15, 'image': 'web/icons/item_img/Pork_and_Eggs_with_salad_hamburger.jpg', 'height': 100, 'width': 100},
      {'name': '奶油湯種厚片', 'price': 20, 'image': 'web/icons/item_img/Pork_and_Eggs_with_salad_hamburger.jpg', 'height': 100, 'width': 100},
      {'name': '奶油貝果', 'price': 30, 'image': 'web/icons/item_img/Pork_and_Eggs_with_salad_hamburger.jpg', 'height': 100, 'width': 100},
      {'name': '香蒜薄片', 'price': 15, 'image': 'web/icons/item_img/Pork_and_Eggs_with_salad_hamburger.jpg', 'height': 100, 'width': 100},
      {'name': '香蒜湯種厚片', 'price': 20, 'image': 'web/icons/item_img/Pork_and_Eggs_with_salad_hamburger.jpg', 'height': 100, 'width': 100},
      {'name': '香蒜貝果', 'price': 30, 'image': 'web/icons/item_img/Pork_and_Eggs_with_salad_hamburger.jpg', 'height': 100, 'width': 100},
      {'name': '巧克力薄片', 'price': 15, 'image': 'web/icons/item_img/Pork_and_Eggs_with_salad_hamburger.jpg', 'height': 100, 'width': 100},
      {'name': '巧克力湯種厚片', 'price': 20, 'image': 'web/icons/item_img/Pork_and_Eggs_with_salad_hamburger.jpg', 'height': 100, 'width': 100},
      {'name': '巧克力貝果', 'price': 30, 'image': 'web/icons/item_img/Pork_and_Eggs_with_salad_hamburger.jpg', 'height': 100, 'width': 100},
      {'name': '藍莓薄片', 'price': 15, 'image': 'web/icons/item_img/Pork_and_Eggs_with_salad_hamburger.jpg', 'height': 100, 'width': 100},
      {'name': '藍莓湯種厚片', 'price': 20, 'image': 'web/icons/item_img/Pork_and_Eggs_with_salad_hamburger.jpg', 'height': 100, 'width': 100},
      {'name': '藍莓貝果', 'price': 30, 'image': 'web/icons/item_img/Pork_and_Eggs_with_salad_hamburger.jpg', 'height': 100, 'width': 100},
    ],

    '蔬菜沙拉系列': [
      {'name': '蛋沙拉', 'price': 50, 'image': 'web/icons/item_img/Pork_and_Eggs_with_salad_hamburger.jpg', 'height': 100, 'width': 100},
      {'name': '火腿沙拉', 'price': 60, 'image': 'web/icons/item_img/Pork_and_Eggs_with_salad_hamburger.jpg', 'height': 100, 'width': 100},
      {'name': '燻雞沙拉', 'price': 60, 'image': 'web/icons/item_img/Pork_and_Eggs_with_salad_hamburger.jpg', 'height': 100, 'width': 100},
    ],

    '點心系列': [
      {'name': '四角薯餅', 'price': 20, 'image': 'web/icons/item_img/Pork_and_Eggs_with_salad_hamburger.jpg', 'height': 100, 'width': 100},
      {'name': '雞優熱狗', 'price': 15, 'image': 'web/icons/item_img/Pork_and_Eggs_with_salad_hamburger.jpg', 'height': 100, 'width': 100},
      {'name': '薯條', 'price': 20, 'image': 'web/icons/item_img/Pork_and_Eggs_with_salad_hamburger.jpg', 'height': 100, 'width': 100},
      {'name': '雞塊小不點', 'price': 20, 'image': 'web/icons/item_img/Pork_and_Eggs_with_salad_hamburger.jpg', 'height': 100, 'width': 100},
      {'name': '麥克雞塊', 'price': 35, 'image': 'web/icons/item_img/Pork_and_Eggs_with_salad_hamburger.jpg', 'height': 100, 'width': 100},
      {'name': '印尼炒麵', 'price': 50, 'image': 'web/icons/item_img/Pork_and_Eggs_with_salad_hamburger.jpg', 'height': 100, 'width': 100},
      {'name': '黃金脆薯', 'price': 30, 'image': 'web/icons/item_img/Pork_and_Eggs_with_salad_hamburger.jpg', 'height': 100, 'width': 100},
      {'name': '卡啦雞（原/辣）', 'price': 40, 'image': 'web/icons/item_img/Pork_and_Eggs_with_salad_hamburger.jpg', 'height': 100, 'width': 100},
      {'name': '香檸雞柳條', 'price': 35, 'image': 'web/icons/item_img/Pork_and_Eggs_with_salad_hamburger.jpg', 'height': 100, 'width': 100},
      {'name': '黃金QQ棒', 'price': 35, 'image': 'web/icons/item_img/Pork_and_Eggs_with_salad_hamburger.jpg', 'height': 100, 'width': 100},
      {'name': '大法式佐紅醬', 'price': 40, 'image': 'web/icons/item_img/Pork_and_Eggs_with_salad_hamburger.jpg', 'height': 100, 'width': 100},
      {'name': '玉米濃湯', 'price': 30, 'image': 'web/icons/item_img/Pork_and_Eggs_with_salad_hamburger.jpg', 'height': 100, 'width': 100},
    ],

    '飲料系列': [
      {'name': '紅茶（中杯）', 'price': 15, 'image': 'web/icons/item_img/Pork_and_Eggs_with_salad_hamburger.jpg', 'height': 100, 'width': 100},
      {'name': '紅茶（大杯）', 'price': 20, 'image': 'web/icons/item_img/Pork_and_Eggs_with_salad_hamburger.jpg', 'height': 100, 'width': 100},
      {'name': '豆漿（中杯）', 'price': 15, 'image': 'web/icons/item_img/Pork_and_Eggs_with_salad_hamburger.jpg', 'height': 100, 'width': 100},
      {'name': '豆漿（大杯）', 'price': 20, 'image': 'web/icons/item_img/Pork_and_Eggs_with_salad_hamburger.jpg', 'height': 100, 'width': 100},
      {'name': '奶茶（中杯）', 'price': 15, 'image': 'web/icons/item_img/Pork_and_Eggs_with_salad_hamburger.jpg', 'height': 100, 'width': 100},
      {'name': '奶茶（大杯）', 'price': 20, 'image': 'web/icons/item_img/Pork_and_Eggs_with_salad_hamburger.jpg', 'height': 100, 'width': 100},
      {'name': '冰釀綠茶（中杯）', 'price': 15, 'image': 'web/icons/item_img/Pork_and_Eggs_with_salad_hamburger.jpg', 'height': 100, 'width': 100},
      {'name': '冰釀綠茶（大杯）', 'price': 20, 'image': 'web/icons/item_img/Pork_and_Eggs_with_salad_hamburger.jpg', 'height': 100, 'width': 100},
      {'name': '咖啡（中杯）', 'price': 25, 'image': 'web/icons/item_img/Pork_and_Eggs_with_salad_hamburger.jpg', 'height': 100, 'width': 100},
      {'name': '咖啡（大杯）', 'price': 30, 'image': 'web/icons/item_img/Pork_and_Eggs_with_salad_hamburger.jpg', 'height': 100, 'width': 100},
      {'name': '可可牛奶（中杯）', 'price': 20, 'image': 'web/icons/item_img/Pork_and_Eggs_with_salad_hamburger.jpg', 'height': 100, 'width': 100},
      {'name': '可可牛奶（大杯）', 'price': 25, 'image': 'web/icons/item_img/Pork_and_Eggs_with_salad_hamburger.jpg', 'height': 100, 'width': 100},
      {'name': '柳橙汁（中杯）', 'price': 20, 'image': 'web/icons/item_img/Pork_and_Eggs_with_salad_hamburger.jpg', 'height': 100, 'width': 100},
      {'name': '柳橙汁（大杯）', 'price': 25, 'image': 'web/icons/item_img/Pork_and_Eggs_with_salad_hamburger.jpg', 'height': 100, 'width': 100},
      {'name': '鮮奶茶（中杯）', 'price': 25, 'image': 'web/icons/item_img/Pork_and_Eggs_with_salad_hamburger.jpg', 'height': 100, 'width': 100},
      {'name': '鮮奶茶（大杯）', 'price': 30, 'image': 'web/icons/item_img/Pork_and_Eggs_with_salad_hamburger.jpg', 'height': 100, 'width': 100},
      {'name': '豆漿紅茶（中杯）', 'price': 20, 'image': 'web/icons/item_img/Pork_and_Eggs_with_salad_hamburger.jpg', 'height': 100, 'width': 100},
      {'name': '豆漿紅茶（大杯）', 'price': 25, 'image': 'web/icons/item_img/Pork_and_Eggs_with_salad_hamburger.jpg', 'height': 100, 'width': 100},
      {'name': '水果冰茶（中杯）', 'price': 25, 'image': 'web/icons/item_img/Pork_and_Eggs_with_salad_hamburger.jpg', 'height': 100, 'width': 100},
      {'name': '水果冰茶（大杯）', 'price': 30, 'image': 'web/icons/item_img/Pork_and_Eggs_with_salad_hamburger.jpg', 'height': 100, 'width': 100},
    ],

    
  };
}
